### PR TITLE
Completed css-brochure-form exercise

### PR DESCRIPTION
**Pull request by techmatlock**
Recording 2024-05-22 at 14 11 34

### CODE REVIEW

**Review by brandon-moy — CHANGES_REQUESTED** [review]
Good look of using a custom CSS variable here to be the color you want! 👍 Great start but a few changes I'd like to see:

- You've taken away the boldness from the LEARN MORE header
- Your "How many engineers..." text should not overflow your select like that. Your inputs should be wider than the label text

When you've made the changes please attach a new picture of the page with the changes you've made.

**Comment by brandon-moy** [comment]
> > Good look of using a custom CSS variable here to be the color you want! 👍 Great start but a few changes I'd like to see:
> > When you've made the changes please attach a new picture of the page with the changes you've made.
> 
> Ok, am i using all the correct selectors correctly such as `fieldset label > input`?
> 
> Screenshot 2024-05-22 at 2 39 17 PM

You're using them properly since you are looking for elements that are children or descendants of other elements. 

However, I would recommend using `class` attributes and selectors instead of using a lot of parent-child or descendant selectors. If you use `class` it's reusable and more specific (by only applying to elements with that `class` attribute) and it will be easier to understand when you need to look through your HTML and CSS files. Instead of looking for `fieldset label > input` we could just add a `class` named something like `form-input` and then select it with `.form-input`.

**Review by brandon-moy — APPROVED** [review]
Great job, approved! Left you a response to your question from the comment. 🫡

**Comment by techmatlock** [comment]
@brandon-moy Awesome thanks!

**Pull request merged**
